# Vanhok Website Configuration for GitHub Pages
title: Vanhok Education Technology
description: Professional education services and IELTS preparation platform
url: https://ankerwong.github.io
baseurl: /vanhok

# Exclude files from processing
exclude:
  - node_modules/
  - ielts/backend/
  - ielts/logs/
  - ielts/ecosystem.config.js
  - "*.log"
  - "*.lock"
  - package*.json