# Vanhok Website Configuration for GitHub Pages
title: Vanhok Education Technology
description: Professional education services and IELTS preparation platform
url: https://ankerwong.github.io
baseurl: /vanhok

# Exclude files from processing
exclude:
  - node_modules/
  - ielts/backend/
  - ielts/frontend/
  - ielts/logs/
  - ielts/data/
  - ielts/ecosystem.config.js
  - ielts/package*.json
  - "*.log"
  - "*.lock"

# Include specific files for IELTS platform
include:
  - ielts/index.html
  - ielts/css/
  - ielts/js/
  - ielts/images/
  - ielts/audio/